language: ruby
rvm:
  - 1.8.7
notifications:
  recipients:
    - jari@holderdeord.no
  irc:
    channels:
      - "irc.freenode.net#holderdeord"
    on_success: change
    on_failure: change
    template:
      - "%{author} | %{commit} | %{message} | %{build_url}"
script: 
  - ./bin/lint.sh
  - 'bundle exec puppet parser validate `find puppet/modules/{hdo,ruby,passenger} -name "*.pp"`'