#
# This file is managed by Puppet. Local edits will be lost.
#

production:
  adapter: postgresql
  encoding: unicode
  database: hdo_production
  pool: 5
  username: hdo
  password: <%= postgresql_hdo_password %>
